### ISSUE TITLE
Support Pandoc 1.16 changes

### ISSUE THREAD

**Issue by nichtich** [nichtich/Pandoc-Elements#11]
Pandoc 1.16 introduces [attributes](https://metacpan.org/pod/Pandoc::Elements#attributes-key-value) for [Images](https://metacpan.org/pod/Pandoc::Elements#Image) and [Links](https://metacpan.org/pod/Pandoc::Elements#Link).

**Comment by bpj** [comment]
I made all (I think) the necessary changes in a fork.

<https://github.com/bpj/Pandoc-Elements/commits/bpj-link-image-attributes>

Do you want a pull request?

**Comment by nichtich** [comment]
Thanks! Have you thought about or even tested whether and how to still make the module work to some degree with Pandoc < 1.16?

On 11. Februar 2016 15:03:06 MEZ, Benct Philip Jonsson <notifications@github.com> wrote:
>I made all (I think) the necessary changes in a fork.
>
><https://github.com/bpj/Pandoc-Elements/commits/bpj-link-image-attributes>
>
>Do you want a pull request?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/nichtich/Pandoc-Elements/issues/11#issuecomment-182877067

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by bpj** [comment]
I have thought about the issue of supporting pandoc < 1.16 as well. My best shot so far is to use a global configuration variable (yes very Old School but it can be set at runtime) so that filters can check for a suitable metadata value, e.g. `oldstyle_links=True` and set the configuration variable accordingly.

**Comment by bpj** [comment]
FWIW jgm just let pandocfilters.py support the latest and greatest. I understand your concern though. I haven't been able to build pandoc on my ancient laptop for some time.

**Comment by bpj** [comment]
Please check out my attempt at a compatibility mode for Link/Image:

https://github.com/bpj/Pandoc-Elements/commit/0fc9fd9080b2b93dc0c4ff90857171d162f4a685

There is an extensive description of what I've done in the commit message.
