### ISSUE TITLE
Add/fix setters

### ISSUE THREAD

**Issue by nichtich** [nichtich/Pandoc-Elements#36]
`$element->content(...)` does not work as expected (not documented anyway).

**Comment by bpj** [comment]
How?

**Comment by nichtich** [comment]
Method `content` is defined at multiple places so setter functionality does not work for all elements. Other getters don't work as setters at all.

On 23. September 2016 16:34:34 MESZ, Benct Philip Jonsson <notifications@github.com> wrote:
>How?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nichtich/Pandoc-Elements/issues/36#issuecomment-249209406

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by bpj** [comment]
Aha. So we basically need to rewrite all the methods named `content` so
that they become setters too? I can do it if you are short on time.

Den 23 sep 2016 16:38 skrev "Jakob Voß" <notifications@github.com>:

> Method `content` is defined at multiple places so setter functionality
> does not work for all elements. Other getters don't work as setters at all.
>
> On 23. September 2016 16:34:34 MESZ, Benct Philip Jonsson <

**Comment by nichtich** [comment]
I'd prefer to avoid explicitly writing accessors for each Element. The extension should be made somewhere around <https://github.com/nichtich/Pandoc-Elements/blob/master/lib/Pandoc/Elements.pm#L103>. Feel free to implement or just add unit tests for later implementation. This issue has no priority for me and I won't involve in coding for Pandoc::Element next week.

**Comment by bpj** [comment]
What about this?

```perl
    for ( my $i = 0 ; $i < @accessors ; $i++ ) {
        my $member = @accessors == 1 ? "\$e->{c}" : "\$e->{c}->[$i]";
        my $code = "my \$e = shift; $member = ( 1 == \@_ ? \$_[0] : [\@_] ) if \@_; return";
        # auto-bless on access via accessor (TODO: move to constructor?)
        $code .= $accessors[$i] =~ s/:\[(.+)\]$//
        ? " [ map { bless \$_, 'Pandoc::Document::$1' } \@{$member} ];"
        : " $member;";
        for ( split '/', $accessors[$i] ) {
            *{ $class . "::$_" } = eval "sub { $code }";
        }
    }
```

**Comment by nichtich** [comment]
Thanks! I'll commit with you as author and add tests.
