### ISSUE TITLE
Run tests against multiple versions of pandoc

### ISSUE THREAD

**Issue by nichtich** [nichtich/Pandoc-Elements#53]
How do we test against multiple versions of pandoc? If we agree on a setup, this can be automated at least for RELEASE_TESTING. How about collecting pandoc executables in a subdirectory structure like this:

    pandoc/1.18/pandoc
    pandoc/1.17.1/pandoc
    ...

These can then be iterated (if the subdirectories exist) and used to make sure that the module works for each version.

**Comment by bpj** [comment]
App::Perlbrew is the answer, or part of it. I already have most perls since 5.8.9 installed, and perlbrew has a command to run stuff on all installed versions. There probably is a way to integrate this with Test::More.

**Comment by bpj** [comment]
@nichtich I just succeeded in building a relocatable pandoc 1.17.2 with stack.  I'll polish the code and doc of my wrapper script and push it ASAP.

**Comment by nichtich** [comment]
Just release Pandoc.pm 0.4.3 to fix the bug with `pandoc --version` - thanks!

**Comment by nichtich** [comment]
I use Ubuntu so I can extract older Pandoc versions from [the official releases](https://github.com/jgm/pandoc/releases/). Not sure which can be executed still...

**Comment by bpj** [comment]
I tried to extract from the distributed packages and found that once I had
figured out the right options for stack it was much less hassle to just
build relocatable binaries. It takes a while and a lot of CPU time though
-- clearly something you want to do while having a break.

Den 9 nov 2016 21:16 skrev "Jakob Voß" <notifications@github.com>:

**Comment by nichtich** [comment]
I included a script to download all releases from GitHub in `xt`. Using the releases works down up to 1.13.2 - I have no executable of 1.12.1 although these should be supported. Maybe checking backwards compatibility here is not important enough.
