### ISSUE TITLE
Rename to Pandoc::Document

### ISSUE THREAD

**Issue by nichtich** [nichtich/Pandoc-Elements#56]
`Pandoc::Elements` is very large. `Pandoc::Document` may be a better name for the distribution with the following parts:

* `Pandoc::Elements`
* `Pandoc::Filter`
* `Pod::Simple::Pandoc`

**Comment by bpj** [comment]
Maybe taking out (some of) the inner packages into their own files?

**Comment by bpj** [comment]
Renaming existing distributions is risky business.  It's maybe better to break out Pandoc::Filter and Pod::Simple::Pandoc into their own distributions.

**Comment by nichtich** [comment]
This package has nicely been packaged for Debian/Ubuntu so better leave it as it is.
