### ISSUE TITLE
Pandoc::Filter fails if multiple items are returned: Pandoc::Walker counter is broken

### ISSUE THREAD

**Issue by jonassmedegaard** [nichtich/Pandoc-Elements#6]
Given this markdown input:
```markdown
a *b* c *d* e
```
and applying this filter:
```perl
use Pandoc::Filter;
use Pandoc::Elements;
pandoc_filter( sub { return [ Str '1', Str '2' ] if ( $_[0]->name eq 'Emph' ); return });
```
I would expect this resulting html:
```html
<p>a 12 c 12 e</p>
```
but instead get this:
```html
<p>a 12 c <em>d</em>12e</p>
```

Reason is that Pandoc::Walker ignores its calibrated counter when stepping through each item.

Fix is to replace Pandow::Walker line 19 from
```perl
foreach my $item (@$ast) {
```
to
```perl
while( my $item = $$ast[$i] ) {
```

**Comment by nichtich** [comment]
Looks like same bug as issue #7 - at least your example is fixed after fixing the issue (release 0.06).
