### ISSUE TITLE
Fix travis for Perl 5.12

### ISSUE THREAD

**Issue by nichtich** [nichtich/Pandoc-Elements#64]
Looks like Dist::Zilla does not support Perl 5.12 anymore - just stop testing it?

**Comment by bpj** [comment]
I'd say yes. The question is whether the min perl version for P::E should
also be bumped to 5.14. It doesn't seem right to claim to support versions
which can't be automatically built & tested.

Den 29 nov 2016 06:52 skrev "Jakob Voß" <notifications@github.com>:

**Comment by nichtich** [comment]
Perl 5.12 runs at cpantesters so I would still support it.
