### ISSUE TITLE
Improve deprecation warning for ->classes

### ISSUE THREAD

**Issue by bpj** [nichtich/Pandoc-Elements#66]
It says "->classes is deprecated, use ->class instead" but in fact code which expects to get an arrayref from `->classes` breaks if you replace all instances of `->classes` with `->class` since the latter returns a string.  I would argue that the real equivalent of `->classes` is `[ $element->keyvals->get_all('class') ]`. It's quite a few characters longer, but it's true!

**Comment by nichtich** [comment]
How about `[ split ' ', $element->class ]`?

**Comment by bpj** [comment]
Well, more or less equivalent.
