### ISSUE TITLE
Why doesn't ->string include CodeBlock?

### ISSUE THREAD

**Issue by bpj** [nichtich/Pandoc-Elements#67]
Why doesn't ->string include CodeBlock? Because its pandocfilters equivalent doesn't? It makes regex matching against the stringified element less convenient as you have to check/query for CodeBlock separately.

**Comment by nichtich** [comment]
Yes I just ported from pandocfilters. Is it a bug or a feature?

On 20. Januar 2017 12:09:28 MEZ, Benct Philip Jonsson <notifications@github.com> wrote:
>Why doesn't ->string include CodeBlock? Because its pandocfilters
>equivalent doesn't? It makes regex matching against the stringified
>element less convenient as you have to check/query for CodeBlock
>separately.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nichtich/Pandoc-Elements/issues/67

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by bpj** [comment]
I'd say a bug. I guess we could ask.
