### ISSUE TITLE
Please add option to *not* process injected items

### ISSUE THREAD

**Issue by jonassmedegaard** [nichtich/Pandoc-Elements#7]
When processing items with Pandoc::Filter (and ultimately Pandoc::Walker), the manipulated items returned back is processed too.

That makes is quite difficult to avoid endless loop when needing to match certain items and not change them but add additional items alongside them - e.g. adding LaTeX code before or after each headline.

Therefore, please implement a flag to skip that processing of returned items.

**Comment by nichtich** [comment]
Injected items should never be processed by the same code which adds them, so this is a bug.

**Comment by jonassmedegaard** [comment]
Quoting Jakob Voss (2015-01-19 10:57:22)
> Injected items should never be processed by the same code which adds 
> them, so this is a bug.

Oh.  I did have trouble understanding in which situations it was a 
feature, but simply assumed you had something clever in mind.

If a bug, then I believe the fix is to *not* call transform() at 
Pandoc::Walker line 24.


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by nichtich** [comment]
fixed in release 0.06
