### ISSUE TITLE
RFC: customizing the return values of ->metavalue and ->string?

### ISSUE THREAD

**Issue by bpj** [nichtich/Pandoc-Elements#73]
# RFC: customizing the return values of -&gt;metavalue and -&gt;string?

I experience some, partly interconnected, irritations with the return values of `->string` and `->metavalue`, in particular `MetaBlocks->metavalue`. Below are some proposals on allowing these methods to take a hash (reference) with options to customize their return value. This would make these methods more flexible and at the same time allow keeping backwards compatibility, since if the option hash is empty the return value will be as it is currently.

1.  Currently the return value of `->string` doesn’t contain the contents of `RawInline` and `RawBlock` elements. While there clearly are situatiions where this is desirable there are also situations where it is not desirable. Also it is probably more often desirable to include `Raw…` content only for some formats. To address this I think it would be a good idea to allow a `raw_formats` parameter to `->string` taking as value either a hashref with format–boolean pairs or an arrayref with formats (which of course is internally converted to a hashref of true booleans), so that the contents of `Raw…` elements with those formats are included in stringified output.

2.  The `->metavalue` and `$meta->value` methods could also benefit from taking parameters, including the same parameters as `->string` to be passed on to `->string` when the `->metavalue` methods call `->string`.

    -   Currently `MetaBlocks->metavalue` returns an arrayref containing the stringification of the children of the `MetaBlocks` element. I’m still to encounter a situation where I want this arrayref rather than a simple string with the stringified children joined with two newlines. Currently I find myself including workaround code which requires loading two extra modules ([Clone] or [Clone::PP] and [Data::Rmap]).

    -   `MetaInlines->metavalue` currently does concatenate the stringification of the children. If `MetaBlocks->metavalue` is made customizable it should be made analogous, although with the opposite default to keep backwards compatibility.

    -   There are situations where I actually want `MetaBool->metavalue` to return a JSON::Boolean object so that I can distinguish it from an ordinary number.

3.  There are situations where I want to convert a metadata tree into a plain tree of hash and array refs but with element objects rather than strings as ‘leaves’, viz.

    | Meta element | Transformed into |
    |--------------|------------------|
    | MetaList     | ARRAY            |
    | MetaMap      | HASH             |
    | MetaString   | Str              |
    | MetaBool     | Str              |
    | MetaInlines  | Span             |
    | MetaBlocks   | Div              |

    There should perhaps be a separate `meta_as_data` method for this.

  [Clone]: https://metacpan.org/pod/Clone
  [Clone::PP]: https://metacpan.org/pod/Clone::PP
  [Data::Rmap]: https://metacpan.org/pod/Data::Rmap

I can have a PR ready in a few days if you think these are good ideas.

**Comment by nichtich** [comment]
Looks reasonable but we should keep it simple. [Pandoc::Metadata](https://metacpan.org/pod/Pandoc::Metadata) is not clear enough about current features ("support common element methods" is not enough). Actually it's the [`value`](https://metacpan.org/pod/Pandoc::Metadata#value(-%5B-$field-%5D-)) method to extend.

We could allow a list of elements to include/exclude with same selector syntax as Pandoc::Filter actions, e.g. e.g. `!RawBlock` 

Converting to JSON::Boolean should be done [like YAML::PP](https://metacpan.org/pod/YAML::PP#Boolean-Handling). 

For 3 a separate method (or alias) makes sense but a better name (`plain`, `simple`, `struct`...).

**Comment by nichtich** [comment]
Please have a look at the current `dev` branch where Converting to JSON::Boolean has been implemented. The `value`/`metavalue` method might further be extended but I tend to change the default to *not* stringify MetaInlines and MetaBlocks.

**Comment by bpj** [comment]
My workaround code for stringifying `MetaBlock`s buried in a meta tree is rather heavy.  It needs to load [Clone][] or [Clone::PP][] and [Data::Rmap][]:

```perl
my $config = clone $self->meta->{$key}; # don't clobber the original

if ( defined $config ) {
    rmap_hash {
        return unless eval { 'MetaBlocks' eq $_->name }; # dies == false is OK
        my $blocks = $_->content;
        $_ = MetaString join "\n\n", map { $_->string } @$blocks;
    } $config;

    $config = $config->metavalue;
```

Some built in solution could do it without those extra dependencies.

[Clone]: https://metacpan.org/pod/Clone
[Clone::PP]: https://metacpan.org/pod/Clone::PP
[Data::Rmap]: https://metacpan.org/pod/Data::Rmap

**Comment by nichtich** [comment]
Would changing `Pandoc::Document::MetaBlocks::value` to join stringified blocks with `\n\n` solve your use case? I thinks this makes more sense than the current action. An alternative action would be to preserve block elements and inline elements, so MetaBlocks becomes an array of block elements. Which of both should be the default?

**Comment by bpj** [comment]
> Would changing Pandoc::Document::MetaBlocks::value to join stringified blocks with \n\n solve your use case? 

Yes.

>I thinks this makes more sense than the current action. An alternative action would be to preserve block elements and inline elements, so MetaBlocks becomes an array of block elements. Which of both should be the default?

That's the question.  I can see relevant use cases for both.  What is problematic is reaching into a structure where MetaBlocks are lists of objects or strings to concatenate them if your use case is like mine.

**Comment by nichtich** [comment]
I releases 0.34. If something is missing, please create a new issue!
