### ISSUE TITLE
Wide character support of ImagesFromCode.pm

### ISSUE THREAD

**Issue by TakeAsh** [nichtich/Pandoc-Elements#79]
I wrote a Pandoc filter `plantuml.pl` for [PlantUML](http://plantuml.com/) .
[PlantUML-Filter.zip](https://github.com/nichtich/Pandoc-Elements/files/1929240/PlantUML-Filter.zip)
But it didn't work for a sample.
```
\Pandoc-Elements\examples>pandoc -s -t html5 --toc --filter "plantuml.pl" -o plantuml-sample.html plantuml-sample.md
->classes is deprecated. Use [ split ' ', $e->class ] instead
Wide character in subroutine entry at \Pandoc-Elements\lib/Pandoc/Filter/ImagesFromCode.pm line 54.
Error running filter \Pandoc-Elements\examples\plantuml.pl:
Filter returned error status 25
```

I found ImagesFromCode.pm failed with Wide character, so I modified it.
`lib/Pandoc/Filter/ImagesFromCode_WChar.pm`
Please review this.

I want to output *.puml and *.svg into a subfolder.
Is there such option in `ImagesFromCode.pm` ?

TakeAsh
https://github.com/TakeAsh

**Comment by nichtich** [comment]
Thanks, for the fix, included in the next release, also an extension to put images in another folder. The  ImagesFromCode filter is still a draft, ideas to improve are welcome!
