### ISSUE TITLE
"dir" option at ImagesFromCode should be relative from the input file.

### ISSUE THREAD

**Issue by TakeAsh** [nichtich/Pandoc-Elements#80]
Thank you for adding "dir" option at ImagesFromCode.
I tried this option for my filter script.
```perl
#!/usr/bin/env perl
use strict;

use Pandoc::Filter;
use Pandoc::Filter::ImagesFromCode;

pandoc_filter 'CodeBlock.plantuml' => Pandoc::Filter::ImagesFromCode->new(
    from => 'puml',
    to   => sub { $_[0] eq 'latex' ? 'eps' : 'svg' },
    dir  => 'images',
    run  => [ 'plantuml', '-T$to$', '-o .', '$infile$' ],
);
```

I ran the command at `Pandoc-Elements` folder.
`Pandoc-Elements>pandoc -s -t html5 --toc --filter "examples/plantuml.pl" -o "examples/plantuml-sample.html" "examples/plantuml-sample.md"`

Then outputed html file was placed in `examples` folder, and the img tags refered `images` subfolder.
```
<div>
  <img src="images/0e76bdfc35464648ab2ec5d9561ed892.svg" class="plantuml" />
</div>
```

But the image files were outputed not `Pandoc-Elements/examples/images` but `Pandoc-Elements/images`.
So, outputed html can't render the img tags correctly.
"dir" option at ImagesFromCode should be relative not from current working folder but from the input file.

**Comment by TakeAsh** [comment]
Is it possible to know the path of the output html file in ImagesFromCode.pm?
If possible, it might be better relative from the the output file rather than the input file.

**Comment by TakeAsh** [comment]
If "dir" doesn't exist, ImagesFromCode will fail.
`failed to create file: images/0e76bdfc35464648ab2ec5d9561ed892.puml`
Before opening $args{infile}, "mkdir" is needed in ImagesFromCode.pm line 72.

**Comment by nichtich** [comment]
The input/output file location is not available (and it could also be STDIN/STDOUT). The problem arises with all kinds of filters that access relative files, e.g. include. The only solution I can think of is to execute conversion from the same directory as the output file.

**Comment by TakeAsh** [comment]
Thank you for consideration.
I see that only Pandoc knows the input/output file location and the filter can't know the location.
You can feel free to close this issue.
Thank you very much!

**Comment by nichtich** [comment]
I [included a PlantUML example](https://github.com/nichtich/Pandoc-Elements/tree/plantuml) based on your code but I get the following error messages:

> [pandoc warning] Could not find image `./activity diagram 1.eps', skipping...
> [pandoc warning] Unable to convert `./plantuml-1.eps' for use with pdflatex.
> [pandoc warning] Unable to convert `./plantuml-3.eps' for use with pdflatex.

I'm not sure whether this is related to Pandoc-Elements or my installation of PlantUML.

**Comment by nichtich** [comment]
By the way, (how) do you want to referred to at [contributors](https://metacpan.org/pod/Pandoc::Elements#CONTRIBUTORS)?

**Comment by TakeAsh** [comment]
I wanted the vector format image for hi-resolution print and for hi-resolution screen.
So, I selected EPS for print and SVG for screen imitating graphviz.pl (PlantUML uses GraphViz internally).
I can open the outputed EPS files by Adobe Illustrator, and they might be looked correct.
But, there might be a problem about EPS in Pandoc.

A workaround is using PNG and wkhtmltopdf.
plantuml.pl
```perl
to   => 'png',
```
MarkDown file
[plantuml-sample.md](https://github.com/nichtich/Pandoc-Elements/files/1939357/plantuml-sample.txt)

Command for HTML
```
>pandoc -s -t html5 --filter plantuml.pl -o plantuml-sample.html plantuml-sample.md
```

Command for PDF
```
>pandoc -s -t html5 --filter plantuml.pl -o plantuml-sample.pdf plantuml-sample.md
```
[plantuml-sample.pdf](https://github.com/nichtich/Pandoc-Elements/files/1939368/plantuml-sample.pdf)

Thank you for proposal about contributors.
If possible, I prefer a link to GitHub profile [TakeAsh](https://github.com/TakeAsh).
Or plain text "TakeAsh".

**Comment by TakeAsh** [comment]
Pandoc + wkhtmltopdf (PNG): [plantuml-sample.pdf](https://github.com/nichtich/Pandoc-Elements/files/1939368/plantuml-sample.pdf), Text in diagrams is converted into bitmap, not scalable, can't copy & paste.
Pandoc (SVG) + Chrome/Vivaldi (Print as PDF): [plantuml-sample_svg.pdf](https://github.com/nichtich/Pandoc-Elements/files/1940271/plantuml-sample_svg.pdf), Text in diagrams is not lost, scalable, can copy & paste.
I don't use Pandoc directly for PDF. I use Pandoc as HTML converter, and get PDF by Chrome/Vivaldi.
