### ISSUE TITLE
"name" option for ImagesFromCode

### ISSUE THREAD

**Issue by TakeAsh** [nichtich/Pandoc-Elements#81]
Thank you for supporting ID as the image file name at 0.35.

On the other hand, PlantUML recommend to specify the file name after the keyword "@startuml".
If omit, I get the warning message.

I don't want to write same thing at separate parts, ID and code block, because it is often to forget to modify another.

So, I want a new option "name".
"name" is the Regular Expression how to capture the name of input and output file from the code block.
[NameOption.zip](https://github.com/nichtich/Pandoc-Elements/files/1934462/NameOption.zip)

```perl
#!/usr/bin/env perl
use strict;

use Pandoc::Filter;
use Pandoc::Filter::ImagesFromCode;

pandoc_filter 'CodeBlock.plantuml' => Pandoc::Filter::ImagesFromCode->new(
    from => 'puml',
    to   => sub { $_[0] eq 'latex' ? 'eps' : 'svg' },
    dir  => 'images',
    name => qr/^\@startuml[ \t]+(?<name>.+)$/m,
    run  => [ 'plantuml', '-T$to$', '-o .', '$infile$' ],
);
```

If "name" is not specified or not match, use ID.
if ID is not specified, use MD5 of code block ordinarily.

TakeAsh
take@TakeAsh.net

**Comment by nichtich** [comment]
I'll make `name` a code reference that gets the full code block element.

Am 21. April 2018 14:05:33 MESZ schrieb TakeAsh68k <notifications@github.com>:
>Thank you for supporting ID as the image file name at 0.35.
>
>On the other hand, PlantUML recommend to specify the file name after
>the keyword "@startuml".
>If omit, I get the warning message.
>
>I don't want to write same thing at separate parts, ID and code block,
>because it is often to forget to modify another.
>
>So, I want a new option "name".
>"name" is the Regular Expression how to capture the name of input and
>output file from the code block.
>[NameOption.zip](https://github.com/nichtich/Pandoc-Elements/files/1934462/NameOption.zip)
>
>```perl
>#!/usr/bin/env perl
>use strict;
>
>use Pandoc::Filter;
>use Pandoc::Filter::ImagesFromCode;
>
>pandoc_filter 'CodeBlock.plantuml' =>
>Pandoc::Filter::ImagesFromCode->new(
>    from => 'puml',
>    to   => sub { $_[0] eq 'latex' ? 'eps' : 'svg' },
>    dir  => 'images',
>    name => qr/^\@startuml[ \t]+(?<name>.+)$/m,
>    run  => [ 'plantuml', '-T$to$', '-o .', '$infile$' ],
>);
>```
>
>If "name" is not specified or not match, use ID.
>if ID is not specified, use MD5 of code block ordinarily.
>
>TakeAsh
>take@TakeAsh.net
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nichtich/Pandoc-Elements/issues/81

-- 
Jakob Voß via Android

**Comment by nichtich** [comment]
Implemented in `dev` branch to be included in the next release.
